apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
data:
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: YWRtaW4=
  MONGO_USERNAME: dXNlcg==
  MONGO_PASSWORD: cGFzc3dvcmQ=
  MONGO_USERS_LIST: dXNlcjpkYkFkbWluLHJlYWRXcml0ZTpwYXNzd29yZA==